#default_provider: google
default_provider: webchooser

providers:
  # !!ווארענונג!! #
  # דאס איז פאר ironpath.ai! #
  - alias: google
    issuer: https://accounts.google.com
    client_id: 435720253354-llei7n4c047mucuo3e81cobukuqlcu80.apps.googleusercontent.com
    client_secret: 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
    scopes: openid email profile
    access_type: offline
    prompt: consent
    redirect_uris:
      - http://localhost:3000/login-callback
      - http://localhost:10001/login-callback
      - http://localhost:11110/login-callback
